export const propertyTypes = [
    "Hotel",
    "Apartel",
    "Hostel",
    "House",
    "Apartment",
    "Condo",
    "Villa",
    "Townhouse",
    "Commercial Space",
    "Parking Space",
    "Function Hall",
    "Swimming Pool",
    "Warehouse",
    "Shop",
    "Meeting Room",
];

export const propertyFacilities = [
    "Wifi",
    "Game console",
    "AC",
    "TV",
    "Fridge",
    "Oven",
    "Dishwasher",
    "Cooking Stove",
    "Microwave",
    "Toaster",
    "Dishes and dining utensils",
    "Washing Machine",
    "Refrigerator",
    "Dryer",
    "Heater",
    "Gym",
    "Pool",
    "Spa",
    "Sauna",
    "Garden",
    "Gated",
    "Security [24-hour]",
    "Carbon Monoxide Detector",
    "Smoke Detector",
    "Fire Extinguisher",
    "Smoke Alarm",
    "Fire Alarm",
    "First Aid Kit",
    "CCTV",
    "Fire Alarm",
    "Cafeteria",
    "Iron",
    "Fans",
    "Linens",
    "Balcony",
    "Coffeemaker",
    "Laundromat nearby",
    "Paid parking",
    "Free parking",
    "Pet Friendly",
    "Smoking Allowed",
    "Hot tub",
    "Indoor Pool",
    "Indoor Fireplace",
    "Outdoor Pool",
    "Hair Dryer",
    "Shampoo",
    "Body Wash/Soap",
    "Towels",
    "Bed Sheets",
]